run: 17
17:
	g++ -std=c++17 -g -Wall -fsanitize=undefined -Wno-deprecated -Wno-unneeded-internal-declaration main.cpp
debug:
	g++ -std=c++17 -g -Wall -fsanitize=undefined -Wno-deprecated -Wno-unneeded-internal-declaration main.cpp
	cat input
	cat input | ./a.out
11:
	g++ -std=c++11 main.cpp -Wall -g -fsanitize=undefined -D_GLIBCXX_DEBUG

